name: "Renew nezha dash app"

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
  schedule:
    - cron: 0 16 * * *

jobs:
  job1-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: Check and download app
        run: |
          NOW=$(cat app/README.md)
          LATEST=$(sudo wget -qO- https://raw.githubusercontent.com/naiba/nezha/master/README.md | grep -oP '(?<=master&label=Dash%20)[^&]*')
          if [[ "$LATEST" =~ ^v([0-9]{1,3}\.){2}[0-9]{1,3}$ && "$NOW" != "$LATEST" ]]; then
            [ -e app/app-$(arch) ] && sudo rm -f app/app-$(arch)
            sudo docker container create --name nezha_app ghcr.io/naiba/nezha-dashboard
            sudo docker container cp nezha_app:/dashboard/app app/app-$(arch)
            sudo docker rm -f nezha_app
            sudo docker rmi -f ghcr.io/naiba/nezha-dashboard
            sudo md5sum app/app-$(arch)
            echo "VERSION=$LATEST" >> $GITHUB_ENV
          fi

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        if: ${{ env.VERSION != '' }}
        with:
          commit_message: Sync app ${{ env.LATEST }} by Github Actions.

  job2-arm64:
    runs-on: self-hosted
    needs: job1-amd64

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: Check and download app
        run: |
          sudo git fetch --all && sudo git reset --hard origin/main
          NOW=$(cat app/README.md)
          LATEST=$(sudo wget -qO- https://raw.githubusercontent.com/naiba/nezha/master/README.md | grep -oP '(?<=master&label=Dash%20)[^&]*')
          if [ "$NOW" != "$LATEST" ]; then
            [ -e app/app-$(arch) ] && sudo rm -f app/app-$(arch)
            sudo docker container create --name nezha_app ghcr.io/naiba/nezha-dashboard
            sudo docker container cp nezha_app:/dashboard/app app/app-$(arch)
            sudo docker rm -f nezha_app
            sudo docker rmi -f ghcr.io/naiba/nezha-dashboard
            sudo md5sum app/app-$(arch)
            echo "VERSION=$LATEST" >> $GITHUB_ENV
            echo "$LATEST" > app/README.md
          fi

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        if: ${{ env.VERSION != '' }}
        with:
          commit_message: Sync app ${{ env.LATEST }} by Github Actions.